name: Event System Application CI

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

       - name: Install Composer dependencies
        run: echo "it's wokring fine"
